#!/bin/bash

# NetSuite Token Based Access Credentials
export ACCOUNT='NETSUITE ACCOUNT ID'
export CONSUMER_KEY='NETSUITE CONSUMER KEY'
export CONSUMER_SECRET='NETSUITE CONSUMER SECRET'
export TOKEN_KEY='NETSUITE TOKEN KEY'
export TOKEN_SECRET='NETSUITE TOKEN SECRET'

# RESTlet Details
export RESTLET_SCRIPT_ID='NETSUITE RESTLET SCRIPT ID'
export RESTLET_DEPLOYMENT_ID='NETSUITE RESTLET DEPLOY ID'